<?php
$z[0]=Array("global","",2397,2429);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",3266,3288);
$z[1][4]['name']="cfg_dbo";
$z[2]=Array("global","",3312,3334);
$z[2][4]['name']="cfg_dbt";
$z[3]=Array("flink","  [field:link /]  ",3370,3447);
$z[3][4]['titlelen']="20";
$z[3][4]['row']="8";
$z[3][4]['type']="text";
$z[4]=Array("global","",3567,3591);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",3679,3704);
$z[5][4]['name']="cfg_tongji";

?>