<?php
$z[0]=Array("global","",381,413);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",550,582);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2177,2209);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channel","\r\n	 <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	 ",2374,2534);
$z[3][4]['row']="6";
$z[3][4]['type']="top";

?>