<?php
$z[0]=Array("global","",214,241);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",367,399);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",536,568);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1955,1982);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",2140,2167);
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("global","",2179,2211);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",2318,2345);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("channel","\r\n	 <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	 ",2384,2544);
$z[7][4]['row']="6";
$z[7][4]['type']="top";

?>