<?php
$z[0]=Array("global","",41,73);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",777,809);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1120,1152);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1910,1942);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1991,2023);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2095,2127);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",2204,2236);
$z[6][4]['name']="cfg_templets_skin";

?>